//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bets
    {
        public int BetID { get; set; }
        public int SessionID { get; set; }
        public decimal BetAmount { get; set; }
        public string Result { get; set; }
        public Nullable<int> WinAmount { get; set; }
    
        public virtual GameSessions GameSessions { get; set; }
    }
}
